# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
