# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_start',
            new_name='start_date',
        ),
    ]
